version: '2.1'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      _JAVA_OPTIONS: -Xms128m -Xmx856m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  sample_producer:
    build: sample_producer
    restart: always
